export const images = {
  astronaut: require("./astronaut.jpg"),
  background_planet: require("./background_planet.png"),
  earth: require("./earth.png"),
  jupiter: require("./jupiter.png"),
  mars: require("./mars.png"),
  mercury: require("./mercury.png"),
  moon: require("./moon.png"),
  neptune: require("./neptune.png"),
  saturn: require("./saturn.png"),
  sun: require("./sun.png"),
  uranus: require("./uranus.png"),
  venus: require("./venus.png"),
  pluto: require("./pluto.png"),
  multi: require("./multi.jpg"),
  training: require("./training.png"),
  star: require("./star.png"),
};
